name: Docker build and push to Docker hub
on:
  push:
    branches:
      - 'main'
env:
  DOCKER_USER: 'jainaveen'
  DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
  REPO_NAME: 'flutter_env'
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Print
        run: echo "$DOCKER_USER      $DOCKER_PASSWORD"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 'jainaveen'
          password: 'dckr_pat_j84mCcVZlG7V-kIb_Dbn1IrOMOM'
      - 
        name: Get current date # get the date of the build
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: jainaveen/flutter_env:latest
          cache-from: type=registry,ref=jainaveen/flutter_env:buildcache
          cache-to: type=registry,ref=jainaveen/flutter_env:buildcache,mode=max